/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DockAppLabel: typeof import('./src/components/DockAppLabel.vue')['default']
    DockAppSwitcher: typeof import('./src/components/DockAppSwitcher.vue')['default']
    DockAvatar: typeof import('./src/components/DockAvatar.vue')['default']
    DockBell: typeof import('./src/components/DockBell.vue')['default']
    DockBookmarks: typeof import('./src/components/DockBookmarks.vue')['default']
    DockBookmarkTile: typeof import('./src/components/DockBookmarkTile.vue')['default']
    DockFallbackBar: typeof import('./src/components/DockFallbackBar.vue')['default']
    DockJana: typeof import('./src/components/DockJana.vue')['default']
    DockNavbar: typeof import('./src/components/DockNavbar.vue')['default']
    DockNotificationDropdown: typeof import('./src/components/notifications/DockNotificationDropdown.vue')['default']
    DockNotificationEmpty: typeof import('./src/components/notifications/DockNotificationEmpty.vue')['default']
    DockNotificationError: typeof import('./src/components/notifications/DockNotificationError.vue')['default']
    DockNotificationLoading: typeof import('./src/components/notifications/DockNotificationLoading.vue')['default']
    DockNotificationRow: typeof import('./src/components/notifications/DockNotificationRow.vue')['default']
    DockPinButton: typeof import('./src/components/DockPinButton.vue')['default']
    DockSearch: typeof import('./src/components/DockSearch.vue')['default']
    DockSearchEmpty: typeof import('./src/components/search/DockSearchEmpty.vue')['default']
    DockSearchError: typeof import('./src/components/search/DockSearchError.vue')['default']
    DockSearchLoading: typeof import('./src/components/search/DockSearchLoading.vue')['default']
    DockSearchModal: typeof import('./src/components/search/DockSearchModal.vue')['default']
    DockSearchRecent: typeof import('./src/components/search/DockSearchRecent.vue')['default']
    DockSearchResultRow: typeof import('./src/components/search/DockSearchResultRow.vue')['default']
    DockSettingsOrganization: typeof import('./src/components/settings/DockSettingsOrganization.vue')['default']
    DockSettingsPersonal: typeof import('./src/components/settings/DockSettingsPersonal.vue')['default']
    DockSidebarToggle: typeof import('./src/components/DockSidebarToggle.vue')['default']
    DockTimer: typeof import('./src/components/DockTimer.vue')['default']
    DockTimerActiveView: typeof import('./src/components/timer/DockTimerActiveView.vue')['default']
    DockTimerError: typeof import('./src/components/timer/DockTimerError.vue')['default']
    DockTimerStaleWarning: typeof import('./src/components/DockTimerStaleWarning.vue')['default']
    DockTimerStartForm: typeof import('./src/components/timer/DockTimerStartForm.vue')['default']
    DockTimerStopForm: typeof import('./src/components/timer/DockTimerStopForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
